import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import ReactQueryProvider from './_lib/queryProvider';

const nunito = Nunito({ subsets: ['cyrillic', 'latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <ReactQueryProvider>
        <body className={nunito.className}>{children}</body>
      </ReactQueryProvider>
    </html>
  );
}
